name: Publish Docker image

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Create `.env`-file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SERVICE_EMAIL: ${{ secrets.SERVICE_EMAIL }}
          envkey_SERVICE_PASSWORD: ${{ secrets.SERVICE_PASSWORD }}
          envkey_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          envkey_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/budgetbuddyde/subscription-service:${{ github.ref_name }}
          mkdir -p artifacts
          docker save ghcr.io/budgetbuddyde/subscription-service:${{ github.ref_name }} > artifacts/docker-image.tar
        env:
          DOCKER_BUILDKIT: 1
          NPM_TOKEN: ${{ secrets.PAT }}

      - name: Save Docker image
        uses: actions/upload-artifact@v2
        with:
          name: docker-artifact
          path: artifacts
          retention-days: 1

  push_image:
    needs: build_image
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve saved Docker image
        uses: actions/download-artifact@v2
        with:
          name: docker-artifact
          path: artifacts

      - name: Load Docker image
        run: |
          cd artifacts
          docker load < docker-image.tar

      - name: Login
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push Docker image
        run: |
          docker push ghcr.io/budgetbuddyde/subscription-service:${{ github.ref_name }}

      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: docker-artifact

  deploy_image:
    needs: push_image
    name: Deploy Docker image to server
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Connect and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ secrets.DOCKER_USER }} --password-stdin
            docker container stop subscription-service
            docker container rm subscription-service
            docker image rm ghcr.io/budgetbuddyde/subscription-service:latest
            docker pull ghcr.io/budgetbuddyde/subscription-service:${{ github.ref_name }}
            docker tag ghcr.io/budgetbuddyde/subscription-service:${{ github.ref_name }} ghcr.io/budgetbuddyde/subscription-service:latest
            docker run -itd --restart on-failure:3 --name=subscription-service ghcr.io/budgetbuddyde/subscription-service:latest
